{
 "title": "DockPulse Observability Panel",
 "tags": [
  "dockpulse",
  "devops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Registered Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockpulse_containers_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockpulse_containers_running", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Host CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockpulse_host_cpu_percentage", "legendFormat": "CPU %" }
   ]
  },
  {
   "title": "Host Memory (RAM) Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockpulse_host_memory_percentage",
     "legendFormat": "RAM %"
    }
   ]
  },
  {
   "title": "Host Disk Space Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockpulse_host_disk_percentage", "legendFormat": "Disk %" }
   ]
  },
  {
   "title": "Containers CPU Usage History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dockpulse_container_cpu_percentage > 0",
     "legendFormat": "{{container_name}} ({{container_id}})"
    }
   ]
  },
  {
   "title": "Containers Memory Usage History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dockpulse_container_memory_used_bytes",
     "legendFormat": "{{container_name}} ({{container_id}})"
    }
   ]
  },
  {
   "title": "Container Lifecycles & States Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dockpulse_container_status",
     "legendFormat": "{{container_name}} [{{status}}]"
    }
   ]
  }
 ]
}